[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST"
    Access-Control-Allow-Headers = "Content-Type"

[[headers]]
  for = "/information.json"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST"
    Access-Control-Allow-Headers = "Content-Type"

